SocialWebsite/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);


/////////////////////////////////////////Pages Routes///////////////////////////////////////
Route::resource('page', 'Page\PageController');
Route::resource('pagePost', 'Page\PagePostController');
//<<<<<<< HEAD
Route::post('/pagelikes','PageLikesController@StorePagesLikes')->name("pageslikes.store");

/////////////////////////////////////////Posts Routes///////////////////////////////////////
Route::resource('timeline', 'Timeline\TimelineController');

Route::post('/pagelikes','PageLikesController@StorePagesLikes')->name("pageslikes.store");

/////////////////////////////////////////Posts Routes///////////////////////////////////////
// =======
Route::resource('timeline', 'Timeline\TimelineController');

// >>>>>>> 430b68d0b5f580084b4243f7126793ccda68d104
Route::get('/home', 'HomePostController@index')->name('home');
Route::get('/post/{id}','SinglePostController@index')->name('home-posts.single');
Route::get('/CreatePost','HomePostController@create')->name('home-post.create');
Route::post('/CreatePost','HomePostController@store')->name('home-post.store');
Route::post('/DeletePost','HomePostController@delete')->name('home-post.delete');
Route::post('/showPost','HomePostController@show')->name('home-post.show');
Route::post('/EditPost','HomePostController@edit')->name('home-post.edit');

Route::post('/home','HomeLikeController@store')->name('like');





// Routes for Friends Managing Controller
Route::resource('/user-friend', 'UserFriendController')->except(['edit']);
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Routes For Profile Controller

Route::get('/profile/settings','Profile\ProfileController@index');
//Route::get('/profile/settings','Profile\ProfileSettingController@updateprofile');
//<<<<<<< HEAD

Route::get('/profile/settings','Profile\ProfileSettingController@index')->name("Restore-View-Settings-Data");//this show the settings view and send user data to the profile settings view 
//=======
// <<<<<<< HEAD
Route::get('/profile/settings','Profile\ProfileSettingController@index')->name("Restore-View-Settings-Data");//this show the settings view and send user data to the profile settings view
//>>>>>>> fc7de589fcf8af6d5ecc742539bc766c3c3ca749
Route::get('/profile','Profile\ProfileController@index')->name('restore-profile-data');//this route call function to bring auth user data
Route::get('/profile/{id}','Profile\OtherUsersProfileController@index')->name('user-profile-data'); //this route to bring another user data and show it in profile data
Route::post('/profile/settings','Profile\ProfileSettingController@updateprofile')->name('update-profile-data');//send new data from profile settings view to
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//<<<<<<< HEAD
//=======
// =======
////<<<<<<< HEAD
Route::get('/profile/settings','Profile\ProfileSettingController@index')->name("Restore-View-Settings-Data");//this show the settings view and send user data to the profile settings view
Route::get('/profile','Profile\ProfileController@index')->name('restore-profile-data');//this route call function to bring auth user data
Route::get('/profile/{id}','Profile\OtherUsersProfileController@index')->name('user-profile-data'); //this route to bring another user data and show it in profile data
Route::post('/profile/settings','Profile\ProfileSettingController@updateprofile')->name('update-profile-data');//send new data from profile settings view to
// >>>>>>> 430b68d0b5f580084b4243f7126793ccda68d104
//>>>>>>> fc7de589fcf8af6d5ecc742539bc766c3c3ca749
//Search Route
Route::get('/search','searchController@getResults')->name('search.results');
//get user profile
Route::get('/user/{name}','Profile\profileController@getProfile')->name('profile.index');

Route::get('/admin','HomeAdminController@index')->name('admin.dashboard');
Route::get('/usertable','UserTableController@index')->name('users-table');
Route::post('/delete_user','UserTableController@delete')->name('user-table.delete');

Route::post('/edit_profile','UserTableController@show')->name('user-table.edit');
Route::post('/comment', 'commentController@index')->middleware('auth');
Route::post('/delete_admin','AdminTableController@delete')->name('admin-table.delete');
Route::post('/edit_profile/{id}','UserTableController@show')->name('user-table.edit');
Route::post('/edit_profileAdmin/{id}','AdminTableController@show')->name('admin-table.edit');
Route::post('/edit_user_profile/{id}','UserTableController@edit')->name('usertable-edituser');
Route::POST('/edit_user_profile/{id}','AdminTableController@edit')->name('admintable-edituser');


Route::get('/addadmin','HomeAdminController@show')->name('show_admin_form');
Route::post('/addadmin','HomeAdminController@add')->name('add_admin');
Route::post('/edit_user_profile/{id}','AdminTableController@edit')->name('admintable-edituser');
Route::get('/admintable','AdminTableController@index')->name('admins-table');

SocialWebsite/resources/views/page/create_page.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
<form method="POST" action="{{route('page.store')}}">
  @csrf
  <div class="form-group">
    <label for="pageName">Name of your page</label>
    <input type="text" name="page_name" class="form-control {{ $errors->has('page_name') ? "is-invalid" : ""}}" id="pageName" placeholder="Page name..." required>
    @if($errors->has('page_name'))
    <div class="invalid-feedback">
        @foreach($errors->get('page_name') as $msg)
          {{$msg}}
        @endforeach
    </div>
    @endif
  </div>
  <div class="form-group">
    <label for="pageDescription">Description</label>
    <textarea class="form-control {{ $errors->has('description') ? "is-invalid" : ""}}" name="description" id="pageDescription" rows="3" placeholder="Page description..." required></textarea>
    @if($errors->has('description'))
    <div class="invalid-feedback">
        @foreach($errors->get('description') as $msg)
          {{$msg}}
        @endforeach
    </div>
    @endif
  </div>
  <button type="submit" class="btn btn-secondary text-light font-weight-bold">Create</button>
</form>
</div>
@endsection

SocialWebsite/resources/views/page/edit_page.blade.php
@extends('layouts/app')

@section('content')
<div class="container">
<form method="POST" action="{{ route('page.update', $page['id']) }}">
  @csrf
  @method('PATCH')
  <div class="form-group">
    <label for="pageName">Name of your page</label>
    <input type="text" name="page_name" class="form-control {{ $errors->has('page_name') ? "is-invalid" : ""}}" id="pageName" value="{{ $page['page_name'] }}" required>
    @if($errors->has('page_name'))
    <div class="invalid-feedback">
        @foreach($errors->get('page_name') as $msg)
          {{$msg}}
        @endforeach
    </div>
    @endif
  </div>
  <div class="form-group">
    <label for="pageDescription">Description</label>
    <textarea class="form-control {{ $errors->has('description') ? "is-invalid" : ""}}" name="description" id="pageDescription" rows="3" required>{{ $page['description'] }}</textarea>
    @if($errors->has('description'))
    <div class="invalid-feedback">
        @foreach($errors->get('description') as $msg)
          {{$msg}}
        @endforeach
    </div>
    @endif
  </div>
  <button type="submit" class="btn btn-success">Edit</button>
</form>
</div>
@endsection

SocialWebsite/resources/views/page/index.blade.php
@extends('layouts/app')
@section('content')
<div class="container-fluid">
@if(!$pages->count())
<h1>There is no pages to show, <a href="{{route('page.create')}}">Create one ?</a></h1>
@else
<h1>All Pages</h1>
@endif
@foreach($pages as $page)
      <div class="card bg-dark border-light" style="width: 19rem;">
        <div class="card-body text-white">
          <h5 class="card-title font-weight-bolder">{{$page['page_name']}}</h5>
          <h6 class="card-subtitle mb-2 text-muted">page owner</h6>
          <p class="card-text">{{$page['description']}}</p>
          <a href="{{route('page.show', $page['id'])}}" class="btn btn-light text-dark font-weight-bold">Show</a>
          <a href="{{route('page.edit', $page['id'])}}" class="btn btn-success text-light font-weight-bold">Edit</a>
          {{-- <a href="" class="btn btn-primary text-light font-weight-bold likebtn">Like</a> --}}
          @php
            $like_count=0;
            $like_status="btn btn-secondary";
            $like_int=0;
          @endphp
          
          @foreach ($page->PagesLikes as $PageLike)
              @php
                if ($PageLike->like==1) {
                  $like_count++;
                }
                if(Auth::check())
                {
                    if($PageLike->like==1 && $PageLike->owner_id==Auth::user()->id)
                    {
                      $like_status="btn btn-primary";
                      
                      $like_int=1;
                    }
                }
              @endphp
          @endforeach

          <button type="button"  data-like={{$like_status}}  data-Page={{$page->id}} data-token="{{Session::token()}}" data-owner={{Auth::user()->id}}
            class="pageslikes btn {{$like_status}} text-light font-weight-bold ">
            Like 
            <span class="glyphicon glyphicon-thumbs-up"></span>
            <b><span class="like_count">{{$like_count}}</span></b>
          </button>



          <form class="float-right" method="POST" action="{{ route('page.destroy', $page['id']) }}">
            @csrf
            @method('DELETE')
            <button type="submit" class="btn btn-danger text-light font-weight-bold">Delete</button>
          </form>
        </div>
      </div>
@endforeach
</div>
@endsection

SocialWebsite/resources/views/page/page_post_edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <form method="POST" action="{{ route('pagePost.update', $pagePost['id']) }}">
    @csrf
    @method('PATCH')
    <div class="form-group">
      <input type="text" name="body" class="form-control {{ $errors->has('body') ? "is-invalid" : ""}}" id="postBody" value="{{ $pagePost->post['body'] }}" required>
      @if($errors->has('body'))
      <div class="invalid-feedback">
          @foreach($errors->get('body') as $msg)
            {{$msg}}
          @endforeach
      </div>
      @endif
    </div>
    <button type="submit" class="btn btn-success">Edit</button>
  </form>
</div>
@endsection

SocialWebsite/resources/views/page/show_page.blade.php
@extends('layouts.app')
@section('content')

<div class="container">

  <form method="POST" action="{{route('pagePost.store')}}">
    @csrf
    <div class="form-group">
      <label for="pageInputPost">Create post</label>
      <input type="text" name="body" class="form-control" id="postContent" placeholder="{{Auth::user()->name}}, Share something with the group..." required>
      <input type="hidden" name="page_id" value="{{$page['id']}}">
    </div>

    <button type="submit" class="btn btn-secondary text-light font-weight-bold">Create</button>
  </form>
  <hr>

  @if($page->page_post->count())
    @foreach($page->page_post as $page_post)
    <div class="card mb-3" style="max-width: 540px;">
      <div class="row no-gutters">
        <div class="col-md-11">
          <div class="card-body">
            <h5 class="card-title">{{Auth::user()->name}}</h5>
            <p class="card-text"><small class="text-muted">{{$page_post->post['created_at']}}</small></p>
            <p class="card-text">{{$page_post->post['body']}}</p>
          </div>
        </div>
        <div class="col-md-1">
          <div class="dropdown float-right">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown">
                <span class="fas fa-edit"></span>
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="{{ route('pagePost.edit', $page_post['id']) }}">Edit</a>
              <form method="POST" action="{{ route('pagePost.destroy', $page_post['id']) }}">
                @csrf
                @method('DELETE')
                <button type="submit" class="dropdown-item text-danger">Delete</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    @endforeach
  @else
    <h1>Nothing to show</h1>
  @endif

</div>


@endsection