SocialWebsite/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);


/////////////////////////////////////////Pages Routes///////////////////////////////////////
Route::resource('page', 'Page\PageController');
Route::resource('pagePost', 'Page\PagePostController');
//<<<<<<< HEAD
Route::post('/pagelikes','PageLikesController@StorePagesLikes')->name("pageslikes.store");

/////////////////////////////////////////Posts Routes///////////////////////////////////////
Route::resource('timeline', 'Timeline\TimelineController');

Route::post('/pagelikes','PageLikesController@StorePagesLikes')->name("pageslikes.store");

/////////////////////////////////////////Posts Routes///////////////////////////////////////
// =======
Route::resource('timeline', 'Timeline\TimelineController');

// >>>>>>> 430b68d0b5f580084b4243f7126793ccda68d104
Route::get('/home', 'HomePostController@index')->name('home');
Route::get('/post/{id}','SinglePostController@index')->name('home-posts.single');
Route::get('/CreatePost','HomePostController@create')->name('home-post.create');
Route::post('/CreatePost','HomePostController@store')->name('home-post.store');
Route::post('/DeletePost','HomePostController@delete')->name('home-post.delete');
Route::post('/showPost','HomePostController@show')->name('home-post.show');
Route::post('/EditPost','HomePostController@edit')->name('home-post.edit');

Route::post('/home','HomeLikeController@store')->name('like');





// Routes for Friends Managing Controller
Route::resource('/user-friend', 'UserFriendController')->except(['edit']);
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Routes For Profile Controller

Route::get('/profile/settings','Profile\ProfileController@index');
//Route::get('/profile/settings','Profile\ProfileSettingController@updateprofile');
//<<<<<<< HEAD

Route::get('/profile/settings','Profile\ProfileSettingController@index')->name("Restore-View-Settings-Data");//this show the settings view and send user data to the profile settings view 
//=======
// <<<<<<< HEAD
Route::get('/profile/settings','Profile\ProfileSettingController@index')->name("Restore-View-Settings-Data");//this show the settings view and send user data to the profile settings view
//>>>>>>> fc7de589fcf8af6d5ecc742539bc766c3c3ca749
Route::get('/profile','Profile\ProfileController@index')->name('restore-profile-data');//this route call function to bring auth user data
Route::get('/profile/{id}','Profile\OtherUsersProfileController@index')->name('user-profile-data'); //this route to bring another user data and show it in profile data
Route::post('/profile/settings','Profile\ProfileSettingController@updateprofile')->name('update-profile-data');//send new data from profile settings view to
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//<<<<<<< HEAD
//=======
// =======
////<<<<<<< HEAD
Route::get('/profile/settings','Profile\ProfileSettingController@index')->name("Restore-View-Settings-Data");//this show the settings view and send user data to the profile settings view
Route::get('/profile','Profile\ProfileController@index')->name('restore-profile-data');//this route call function to bring auth user data
Route::get('/profile/{id}','Profile\OtherUsersProfileController@index')->name('user-profile-data'); //this route to bring another user data and show it in profile data
Route::post('/profile/settings','Profile\ProfileSettingController@updateprofile')->name('update-profile-data');//send new data from profile settings view to
// >>>>>>> 430b68d0b5f580084b4243f7126793ccda68d104
//>>>>>>> fc7de589fcf8af6d5ecc742539bc766c3c3ca749
//Search Route
Route::get('/search','searchController@getResults')->name('search.results');
//get user profile
Route::get('/user/{name}','Profile\profileController@getProfile')->name('profile.index');

Route::get('/admin','HomeAdminController@index')->name('admin.dashboard');
Route::get('/usertable','UserTableController@index')->name('users-table');
Route::post('/delete_user','UserTableController@delete')->name('user-table.delete');

Route::post('/edit_profile','UserTableController@show')->name('user-table.edit');
Route::post('/comment', 'commentController@index')->middleware('auth');
Route::post('/delete_admin','AdminTableController@delete')->name('admin-table.delete');
Route::post('/edit_profile/{id}','UserTableController@show')->name('user-table.edit');
Route::post('/edit_profileAdmin/{id}','AdminTableController@show')->name('admin-table.edit');
Route::post('/edit_user_profile/{id}','UserTableController@edit')->name('usertable-edituser');
Route::POST('/edit_user_profile/{id}','AdminTableController@edit')->name('admintable-edituser');


Route::get('/addadmin','HomeAdminController@show')->name('show_admin_form');
Route::post('/addadmin','HomeAdminController@add')->name('add_admin');
Route::post('/edit_user_profile/{id}','AdminTableController@edit')->name('admintable-edituser');
Route::get('/admintable','AdminTableController@index')->name('admins-table');

SocialWebsite/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{$settings->getSetting('NETWORK_NAME')}}</title>

    <!-- Scripts -->
    <!-- <script src="{{ asset('js/app.js') }}" defer></script> -->
    <script>
      var token = "{{csrf_token()}}"
    </script>
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
    <!-- Icons -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <!-- Styles -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <script src="http://code.jquery.com/jquery-3.3.1.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker3.min.css" rel="stylesheet">
    {{-- profile settings sources --}}
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>

</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ route('timeline.index') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                      @auth
                      <li class="nav-item">
                        <a class="nav-link active" href="{{route('timeline.index')}}"><i class="fas fa-home"></i> Home</a>
                      </li>
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-newspaper"></i> Posts</a>
                        <div class="dropdown-menu">
                          <a class="dropdown-item" href="{{url('CreatePost')}}"><i class="fas fa-file-alt"></i> Create Post</a>
                          <a class="dropdown-item" href="{{url('home')}}"><i class="fas fa-file-alt"></i> Show Posts</a>
                        </div>
                      </li>
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-newspaper"></i> Pages</a>
                        <div class="dropdown-menu">
                          <a class="dropdown-item" href="{{route('page.index')}}">All pages</a>
                          <a class="dropdown-item" href="{{route('page.create')}}">Create page</a>
                        </div>
                      </li>

                      <li class="nav-item">
                        <a class="nav-link" href="#"><i class="fas fa-phone"></i> Contact</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="#"><i class="fas fa-info-circle"></i> About</a>
                      </li>
                      <li class="nav-item">
                          <span class="badge badge-pill badge-primary" style="float:right;margin-bottom:-10px;">
                            @php
                              $user = auth()->user();
                              $userRequests = $user->receivedFriends()->where('is_accepted', 0)->get();

                            @endphp
                            {{$userRequests->count()}}
                          </span>
                          <a class="nav-link" href="{{route('user-friend.index')}}">Friend Request <span class="sr-only">(current)</span></a>
                      </li>
                      <li class="nav-item" style='margin-left:40px;margin-top:7px;'>
                        <form action="{{route('search.results')}}" role="search">
                            <div class="input-group">
                                <input type="text" class="form-control" name="q"
                                placeholder="Search For..."> <span class="input-group-btn">
                                <button type="submit" class="btn btn-default">
                                <span class="fas fa-search"></span>
                                </button>
                                </span>
                            </div>
                        </form>
                      </li>
                      @endauth
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav float-right">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                                  <a class="dropdown-item" href="{{route('restore-profile-data')}}">
                                      {{ __('Profile') }}
                                  </a>

                                  <a class="dropdown-item" href="{{route('Restore-View-Settings-Data')}}">
                                      {{ __('Settings') }}
                                  </a>

                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <script>
    $(function(){
      $('.datepicker').datepicker({
      format: 'mm/dd/yyyy'
      });
    })
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="{{url('/js/pageslikes.js')}}"></script>

</body>
</html>